# Just the CLI necesseties. Installed everywhere: linux and mac, codespaces, etc

brew 'ack'
brew 'bat'
brew 'ccat'
brew 'fzf'
brew 'git'
brew 'gpg'
brew 'htop'
brew 'httpie'
brew 'jq'
brew 'parallel'
brew 'pdsh'
brew 'ripgrep'
brew 'tmux'
brew 'tree'
brew 'vegeta'
brew 'vim'
brew 'yarn'

tap 'homebrew/bundle'
